name: Basic

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: cat README.md
